# ----------------------------------------------------------------------------#
# Commissioning File
# ----------------------------------------------------------------------------#
# Manufacturer: Siemens
# Device: S7-1200
# Copyright: Cybus GmbH (2018)
# Contact: support@cybus.io
# ----------------------------------------------------------------------------#
# Source Interface Definition - S7 Protocol
# ----------------------------------------------------------------------------#
source:
  driver: s7
  connection:
    protocol: s7.tcp
    host: {{S7 Ip address}}
    port: 102
    rack: 0
    slot: 1
    interval: 500
  defaults: 
    operation: write
# ----------------------------------------------------------------------------#
# Target Interface Definition - MQTT (Cybus Connectware Broker)
# ----------------------------------------------------------------------------#
target:
  driver: mqtt
  defaults:
    operation: subscribe
    topicPrefix: io/cybus/learn/{{S7 ID}}
# ----------------------------------------------------------------------------#
# Mappings
# ----------------------------------------------------------------------------#
mappings:
- source:
    typeAddress: QX0.0
  target:
    topic: "out/0"
- source:
    typeAddress: QX0.1
  target:
    topic: "out/1"
- source:
    typeAddress: QX0.2
  target:
    topic: "out/2"
- source:
    typeAddress: QX0.3
  target:
    topic: "out/3"
- source: 
    typeAddress: QB0
  target:
    topic: "out/all"
- source: 
    operation: subscribe
    typeAddress: IB0
  target: 
    operation: write
    topic: "in/all"